### PR TITLE
Update to latest logback and jackson version

### PR DESCRIPTION
**Pull request by makkan**
Updated to use latest logback and jackson to support framework such as dropwizard

### CODE REVIEW

**Comment by davidkarlsen** [comment]
Seems to be a lot of whitespace changes. Should not only the version elements change in the diff?

**Comment by makkan** [comment]
Intellij which automatic removed extra spaces from the test class. Needed to update the tests due to that TeztConstants had been removed and that the context was not set in EclipseLogAppenderTest.

**Comment by davidkarlsen** [comment]
lgtm
@ceki ?

**Review by tony19 — APPROVED** [review]

**Comment by tzachz** [comment]
[As far as I can see](https://mvnrepository.com/artifact/ch.qos.logback.contrib/logback-json-classic) this wasn't ever published, any chance this change can be published as a 0.1.16 version?

**Pull request merged**
